import com.infmenergy.ui.screens.bottomnavigation.usage.ServiceAddress

data class SampleDetailsPlan(
    val accountStatus: String,
    val applicationErrors: Any?,
    val brandSlug: String?,
    val campaignId: String?,
    val commodity: String?,
    val contractAccountId: String?,
    val contractExpirationDate: String?,
    val contractId: String?,
    val docUrl: String?,
    val docnr: String?,
    val earlyCancellationFee: String?,
    val elecontractTermMyPlan: String?,
    val email: String?,
    val endingCycle: String?,
    val epnetId: Any?,
    val errorCode: String?,
    val errorMessage: String?,
    val firstName: String?,
    val gascontractTermMyPlan: Any?,
    val imageNamesArray: Any?,
    val isEVPlan: Boolean?,
    val lastName: String?,
    val monthlyFee: String?,
    val northeastId: String?,
    val offerCode: String?,
    val partnerCode: String?,
    val phone: String?,
    val planDetail: String?,
    val planTerm: String?,
    val planType: String?,
    val price: String?,
    val pricingTerm: String?,
    val productName: String?,
    val promoCode: String?,
    val rateCategory: String?,
    val rateType: String?,
    val rewards: List<String>?,
    val serviceAddress: ServiceAddress?,
    val serviceState: Any?,
    val sku: String?,
    val startCycle: String?,
    val unitOfMeasure: String?,
    val utility: String?,
    val utilityAccountNumber: String?,
    val utilityName: String?
)


